create table hello (
                       id bigint not null,
                       name varchar(255),
                       primary key (id)
);
create table mb (
                    member_id bigint not null,
                    age integer not null,
                    username varchar(255),
                    team_id bigint,
                    primary key (member_id)
);
create table member (
                        id bigint generated by default as identity,
                        created_date timestamp,
                        modified_date timestamp,
                        email varchar(255) not null,
                        name varchar(255) not null,
                        picture varchar(255),
                        role varchar(255) not null,
                        primary key (id)
);
create table posts (
                       id bigint generated by default as identity,
                       created_date timestamp,
                       modified_date timestamp,
                       author varchar(255),
                       content TEXT not null,
                       title varchar(500) not null,
                       primary key (id)
);
create table team (
                      team_id bigint not null,
                      name varchar(255),
                      primary key (team_id)
);
alter table mb
    add constraint FKbf7ag6kgol5xm4iuegep6itq
        foreign key (team_id)
            references team;

create sequence hibernate_sequence START WITH 1 INCREMENT BY 1;